border_force_drt_flights_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BorderForceDrtFlightsBundle:Default:index }

border_force_drt_get_flights:
    resource: "@BorderForceDrtFlightsBundle/Controller/FlightController.php"
    type:     rest