border_force_drt_flights:
    resource: "@BorderForceDrtFlightsBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
