<?php

namespace BorderForce\Drt\FlightsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightRepository extends EntityRepository
{
  
  public function findByFlightNumberAndScheduledDate($flightNumber, $scheduledDate) {
    
    try {
      $flight = $this->getEntityManager()->createQuery(
        'select f from BorderForceDrtFlightsBundle:Flight f
         where f.flightNumber = :flightNumber and
         f.scheduledDate = :scheduledDate')
        ->setParameter('flightNumber',  $flightNumber)
        ->setParameter('scheduledDate', $scheduledDate)
        ->getSingleResult();
    }
    catch (\Doctrine\Orm\NoResultException $e) {
      $flight = null;
    }
    return $flight;
  }
  
  public function generateId() {
    $em        = $this->getEntityManager();
    $tableName = $em->getClassMetadata('BorderForceDrtFlightsBundle:Flight')->getTableName();
    $stmt = $this->getEntityManager()
      ->getConnection()
      ->prepare('SELECT max(id) AS maxid FROM ' . $tableName);
    $stmt->execute();
    $res = $stmt->fetch();
    return intval($res['maxid']) + 1;
  }
}
